# -*- coding: utf-8 -*-
"""AI-Powered Notes Summariser (V4 – Multi-Format Version).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDXSAm-sMVkvWvkihkVUd73eMV8uJkWj
"""

# 🧠 AI-Powered Notes Summariser (V4 – Multi-Format File Upload Version)

# ✅ Install required libraries
!pip install transformers torch textwrap3 pdfplumber python-docx

from transformers import pipeline
import textwrap
from google.colab import files
import pdfplumber
import docx

# Load summarization model
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

print("🧠 AI-Powered Notes Summariser (V4 - Multi-Format File Upload Version)")
print("-----------------------------------------------------------")
print("📂 Please upload your .txt, .pdf, or .docx file below:")

# Upload file
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
print(f"\n✅ File uploaded: {file_name}")

# Extract text depending on file type
if file_name.endswith(".txt"):
    with open(file_name, "r", encoding="utf-8") as f:
        text = f.read()

elif file_name.endswith(".pdf"):
    text = ""
    with pdfplumber.open(file_name) as pdf:
        for page in pdf.pages:
            text += page.extract_text() + "\n"

elif file_name.endswith(".docx"):
    doc = docx.Document(file_name)
    text = "\n".join([p.text for p in doc.paragraphs])
else:
    raise ValueError("Unsupported file format. Please upload .txt, .pdf, or .docx")

# Clean and validate text
text = text.strip().replace("\n\n", "\n")
if not text:
    raise ValueError("No readable text found in the uploaded file.")

print(f"📄 File loaded successfully ({len(text)} characters)")
print("⚙️ Generating summary... please wait.\n")

# Summarize text in chunks (for large documents)
max_chunk = 1000
summary = ""

for i in range(0, len(text), max_chunk):
    chunk = text[i:i+max_chunk]
    result = summarizer(chunk, max_length=150, min_length=40, do_sample=False)
    summary += result[0]['summary_text'] + " "

# Display and save
summary_text = summary.strip()
print("🧠 Summary:\n")
print(textwrap.fill(summary_text, width=80))

# Save summary to file
output_file = "summary_output.txt"
with open(output_file, "w", encoding="utf-8") as f:
    f.write(summary_text)

print(f"\n💾 Summary saved as '{output_file}' — preparing download...")
files.download(output_file)